### PR TITLE
Initial flux capac site

### PR DESCRIPTION
**Pull request by kbcoding517**
Initial website done

### CODE REVIEW

**Review by boc4life — COMMENTED** [review]
looks good!

**Comment by Koutouzosm** [comment]
Not good enough clean up code and resubmit

**Comment by kbcoding517** [comment]
That's not cool bro, this code is fine.

**Comment by Koutouzosm** [comment]
Sorry you are correct

**Review by Koutouzosm — APPROVED** [review]

**Comment by kbcoding517** [comment]
@boc4life  can you please approve, we need to ge this feature in before break.

**Review by boc4life — COMMENTED** [review]
even better than before

**Review by boc4life — APPROVED** [review]

**Pull request merged**
